apiVersion: apps/v1
kind: Deployment
metadata:
  name: adv-msa-service-user
  labels:
    app: adv-msa-service-user
spec:
  replicas: 2
  selector:
   matchLabels:
    app: adv-msa-service-user
  template: 
    metadata:
      labels:
        app: adv-msa-service-user
    spec:
      containers:
      - name: adv-msa-service-user
        image: mvarun96/adv-msa-service-user
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: SPRING_DATASOURCE_URL
          value: mysql-5kp6z:3306
        - name: OPENTRACING_JAEGER_UDP_SENDER_HOST
          valueFrom:
            configMapKeyRef:
              name: jaeger-config
              key: opentracing.jaeger.udp-sender.host
        - name: OPENTRACING_JAEGER_UDP-SENDER_PORT
          valueFrom:
            configMapKeyRef:
              name: jaeger-config
              key: opentracing.jaeger.udp-sender.port