FROM openjdk:8
ADD target/nagp-adv-msa-service-orderdetails-1.0.0-SNAPSHOT.jar nagp-adv-msa-service-orderdetails-1.0.0-SNAPSHOT.jar
EXPOSE 8084
CMD java -jar nagp-adv-msa-service-orderdetails-1.0.0-SNAPSHOT.jar